# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#PRODUCTS (problemi nell'assegnamento data)
Product.delete_all
products = Product.create([{name: 'Arc', must_have: true,
                            description: 'Drawing inspiration from tensile fabric structures, the form of the "arc" table is generated by software developed to create flowing architectural designs. The sculptural base is a single sweeping form anchored by three legs - between each extension, the material curves upwards to balance the table top. The top is a tempered glass disc, measuring either 140 or 150 centimetres in diameter, and is available in an extra light finish. Three thin stainless steel plates are UV bonded to the glass and allow the base to be safely and discreetly secured using just three small screws.Early prototypes used self-skinning polyurethane foam and aluminium to determine the form the base of the table would take. However for production, the design team investigated the possible use of "Ductal", a self-coloured, lightweight fibre-filled concrete material previously used by the practice for building projects. Its strength and comparative lightness presented an interesting paradox and the material can be moulded to allow the wall thickness and details to be accurately controlled. Ductal is also waterproof and the mass-coloured base ensures the colour stays fresh throughout its lifespan.', image_url: 'imagearc.jpg',
                           tech_image_url: 'tech_imagearc.jpg',datasheet: 'height 110 cm, width 100 cm'},
                           {name: 'Less less', must_have: true,
                            description: 'Fantastic table', image_url: 'imagelessless.jpg',
                            datasheet: 'height 166 cm, width 100 cm'},
                            {name: 'Biotab', must_have: false,
                            description: 'Fantastic biotable', image_url: 'imagebiotab.jpg',
                            datasheet: 'height 120 cm, width 80 cm'}
                          ])

#DESIGNERS
Designer.delete_all
designers = Designer.create([{name: 'Enrico Coveri', bio: 'Enrico Coveri was born in Florence, Italy in 1952. He studied at the Accadema delle Belle Arti in Florence. In 1973, he began working as freelance designer, creating knitwear and sportswear lines for three collections, Toché, Gentry and Tycos making his mark by being one of the first designers to use soft pastel shades. He moved to Paris in 1978 to work at the Espace Cardin, the vast design institute set up by Pierre Cardin. Shortly after that, he returned to Italy and established his own company in 1979. Each season the company produced a ready-to-wear women\'s line and several less expensive boutique collections for men, women, teenagers, and children, as well as a vast array of subsidiary Coveri accessory products such as shoes, bags, hats, scarves, and gloves. Enrico exceptionally collaborated this year with HBC for a special line of design furniture',
                              image_url: 'fotoenrico.jpg',top: false},
			     {name: 'Marc Sadler', bio: 'Marc Sadler was born in Austria. He is a French citizen and at present lives in Milan. He graduated from the Ecole Nationale Supérieure des Arts Décoratifs (Paris) in 1968, at the end of the first industrial design course (it had the well-chosen definition of esthétique industrielle), a branch of learning that was already regarded as a separated branch of learning as to architecture. Devoted from the start to the experimentation with plastic materials (subject of his degree thesis and of his personal curiosity) since the 70ies he brought to perfection the very first ski-boot in thermoplastic material, subsequently industrialized by the Italian firm Caber.The way was opened towards a long and fruitful collaboration with Caber (afterwards known as Lotto), that led him to the patenting of the ski-boot with symmetric shell, the most successful ski-boot for several years all over the world. This represented the origin of his specialization as a ?designer for sport sector, that led him to the cooperation with the most important multinational sport Companies in the United States, Asia, Japan and Europe.His professional path allowed him to mature a varied experience regarding both materials and manufacturing processes. The source from sports field, where research and experimentation on new materials and working technologies are more widely diffused, allowed him to export ideas and knowledge towards fields in which design (with a classical meaning) is deep-rooted for a long time.Stateless in a broad sense (he lived and practiced his job in France, United States, Asia and Italy), toady he is (probably) temporarily settled in Milan. He constantly cooperates with very important firms in the fields of home furnishing, big and small household appliances, lighting, and of more technically advanced products as well, in addition to his collaborations in the field of sport.',
                              image_url: 'fotosadler.jpg',top: true},
			     {name: 'Margherita Bonetti', bio: 'Margherita (Meggy) Bonetti is a young italian designer, who is attending her Bachelor in Design at the Naba Academy in Milan. In spite of her young age she has obtained impressive results and won many important prizes, Createur de l\'Annee (Paris), Compasso d\'Oro ADI (Milano), Design Plus (Frankfurt), Auszeichnung fur Gutes Design (Hannover).',
                              image_url: 'fotomeggy.jpg',top: false},
			     {name: 'Valentina Giulini', bio: 'Valentina Giulini is a young italian designer. She achieved a Bachelor in Design at the Naba Academy in Milan and a Master of Arts in Graphic Branding and Identity at the London College of Communication. She has worked for many major companies in Italy and in London. HBC has required her collaboration for a collection of chairs of fashionable design',
                              image_url: 'fotovale.jpg',top: false}
                            ])

#PRODUCT TYPES
ProductType.delete_all
product_types = ProductType.create([{name: 'tables', image_url: 'tablesimage.jpg'},
                                     {name: 'chairs', image_url: 'chairsimage.jpg'}
                                    ])

#EVENTS
Event.delete_all
events = Event.create([{name: 'Salone del mobile 2013', location: 'The new Milan Fair Rho Pero is one of the largest fairground world-wide with 8 large pavilions for indoor exhibitions and 60,000 squared meters for outdoor exhibitions. The Milan Fair is one of the most important in the international trade fair sectors.The new fairground of Milan in Rho Pero has a distance of 15 km to Milan city center. It is connected by the motorways A4 Turin-Milan-Venice, A8/A9 Milan-Airport Malpensa, Varese/Como as well as by the West tangential. For visitors and exhibitors are more than 14.000 parking lots with modern park system at disposal. The red underground line 1 has been extended up to the fair stop Rho. Thus the new fairground can be attained easily from the Milan city center by public transport.',
                        description: '"The Milan International Furniture Fair (Italian: Salone Internazionale del Mobile di Milano) is a furniture fair held annually in Milan. It is the largest trade fair of its kind in the world. The show showcases the latest in furniture and design from countries around the world. It is considered a leading venue for the display of new products by designers of furniture, lighting and other home furnishings. The show, also known as "Salone", "Milano Salone" and "Milan Design Week," is held every year, usually in April, in the FieraMilano complex in the Milan metropolitan area town of Rho.', image_url: 'salone.jpg'},
                      {name: 'Expo 2015', location: 'Rho',
                        description: 'Evento internazionale', image_url: 'expo.jpg'}
                      ])

#COUNTRIES
Country.delete_all
countries = Country.create([{name: 'Australia'},
                            {name: 'France'},
                            {name: 'Germany'},
                            {name: 'Italy'},
                            {name: 'Spain'},
                            {name: 'UK'},
                            {name: 'USA'}
                           ])

#COUNTIES
County.delete_all
counties = County.create([
                          {name: 'Lombardia'},
                          {name: 'Basilicata'},
                          {name: 'Marche'},
                          {name: 'Veneto'},
                          {name: 'Lazio'},
                          {name: 'Kent'},
                          {name: 'Sussex'},
                          {name: 'California'},
                          {name: 'New York'},
                          {name: 'Texas'},
                          {name: 'Massachussets'}
                         ])

#SHOPS
Shop.delete_all
shops = Shop.create([
                        {address: "Largo Quinto Alpini,15, Milano", email:"best.shop@mail.it",
                         name:"HBC flagship store Milano", county: "Lombardia", country: "Italy",
                         tel:"02/567890", shop_type:"flagship store"}   ,
                        {address: "via Baldinucci, 78, Milano", email:"hbc.shop@mail.it",
                         name:"HBC design store", county: "Lombardia", country: "Italy",
                         tel:"02/4567890", shop_type:"flagship store"}
                    ])

#PRODUCT IMAGES
ProductImage.delete_all
product_images = ProductImage.create([
                            {image_url: "imagearc2.jpg", product_id: 0},
                            {image_url: "imagearc3.jpg", product_id: 0},
                            {image_url: "imagearc4.jpg", product_id: 0},
                            {image_url: "imagearc5.jpg", product_id: 0}
                                     ])



#EVENT IMAGES
EventImage.delete_all
event_images = EventImage.create([
                        {image_url: "salone1.jpg", event_id: 0},
                        {image_url: "salone2.jpg", event_id: 0},
                        {image_url: "salone3.jpg", event_id: 0},
                        {image_url: "salone4.jpg", event_id: 0},
                        {image_url: "salone5.jpg", event_id: 0}
                    ])



#JOIN TABLE DESIGNERS_PRODUCTS
products[0].designers << Designer.find_by_name('Enrico Coveri')
products[1].designers << Designer.find_by_name('Enrico Coveri')
products[2].designers << Designer.find_by_name('Enrico Coveri')
products[0].designers << Designer.find_by_name('Marc Sadler')

#JOIN TABLE EVENT_PRODUCTS
products[0].events << Event.find_by_name('Salone del mobile 2013')
products[0].events << Event.find_by_name('Expo 2015')

#JOIN TABLE PRODUCTS_SUGGESTED_PRODUCTS
products[0].suggested_products << Product.find_by_name('Biotab')
products[0].suggested_products << Product.find_by_name('Less less')

#JOIN TABLE PRODUCTS_SHOPS
products[0].shops << Shop.all
products[1].shops << Shop.all


#RELATION PRODUCT_TYPE_PRODUCTS
product_types[0].products << Product.where(:name => "Arc")
product_types[0].products << Product.where(:name => "Biotab")

#RELATION COUNTRY_COUNTIES
countries[3].counties << County.where(:name=>'Lombardia')
countries[3].counties << County.where(:name=>'Basilicata')
countries[3].counties << County.where(:name=>'Marche')
countries[3].counties << County.where(:name=>'Veneto')
countries[3].counties << County.where(:name=>'Lazio')
countries[5].counties << County.where(:name=>'Kent')
countries[5].counties << County.where(:name=>'Sussex')
countries[6].counties << County.where(:name=>'California')
countries[6].counties << County.where(:name=>'New York')
countries[6].counties << County.where(:name=>'Texas')
countries[6].counties << County.where(:name=>'Massachussets')

#RELATION PRODUCT_IMAGES
products[0].product_images << ProductImage.where(:product_id=>0)

#RELATION EVENT_IMAGES
events[0].event_images <<  EventImage.where(:event_id=>0)